### PR TITLE
Upgrade to JBrowse V2

### LINKED ISSUE #102: JBrowse reload shows 404
CFD6A808-FDA0-4CF5-8E48-A08ED0E9A1ED

Repro:

1. Go to https://dev.serratus.io/explorer?run=ERR2756788
2. Select JBrowse link (https://dev.serratus.io/jbrowse?bam=ERR2756788)
3. Reload the page

Explanation:

- With step (2), the URL changes to the URL changes to https://dev.serratus.io/jbrowse?loc=NC_045512.2%3A1847..3372&tracks=Cov3ma%20Reference%20Sequence%2C&highlight=.
- Seems like with `bam=ERR2756788` is now missing from query parameters, which causes the error.

### LINKED ISSUE #103: JBrowse Error HTTP 416
SRR9966511 NC_002532.2 JBrowse screenshot

Repro steps:

1. Go to https://dev.serratus.io/explorer?run=SRR9966511
2. Select **Arteriviridae** > **NC_002532.2** > **View Alignment** (links to https://dev.serratus.io/jbrowse?bam=SRR9966511&loc=NC_002532.2)

### LINKED ISSUE #127: Current JBrowse implementation prevents nested routes
Been trying to make `/explorer/rdrp` work, but keep running into this error:

nested-route-jbrowse

Note that `http://localhost:3000/explorer/dist/0.bundle.js` should be `http://localhost:3000/dist/0.bundle.js`.

This might be because we have compiled JBrowse files in our source (reason: https://github.com/serratus-bio/serratus.io/pull/77#discussion_r472482617). We can observe it building the path to `*.bundle.js` relative to the current path:

```
return i.p+""+({}[t]||t)+".bundle.js"
```

I've tried using `createBrowserHistory({ basename: '/' })` and removing `exact` from the `Route`, but no luck.

Reference:

- https://stackoverflow.com/questions/50275901/react-routing-path-not-working-bundle-not-found

### PR DESCRIPTION
**Pull request by victorlin**
Preview link: https://dev-jbrowse.serratus.io/

As suggested by @cmdcolin in https://github.com/serratus-bio/serratus.io/issues/25#issuecomment-869060841.

- closes #127
- closes #102
- closes #103

Note:

- `chunkSizeLimit` used to be 4,0000,000; it is now 100,000,000 [[src]](https://github.com/GMOD/jbrowse-components/blob/b2234191fd2023fd7be635e481d4459f7107030e/plugins/alignments/src/BamAdapter/configSchema.ts#L23-L25)

### CODE REVIEW

**Comment by victorlin** [comment]
Hey @cmdcolin, thanks for the pointer! The LGV works great after a bit of tinkering. One question: is there a way to "lazy load" large alignments like before? Example:

Old: delays load until zooming into a smaller region

https://serratus.io/jbrowse?bam=SRR9966509&loc=MG197718.1

Screen Shot 2021-06-28 at 21 58 50

New: attempts to load all at once, which takes ~1m

https://dev-jbrowse.serratus.io/jbrowse?bam=SRR9966509&loc=MG197718.1

Screen Shot 2021-06-28 at 21 57 20

**Comment by cmdcolin** [comment]
(you can possibly use v1.1.0 of the package to avoid the issue mentioned in (2), the slowness was accidentally introduced in v1.2.0)

**Comment by victorlin** [comment]
@cmdcolin thanks for the tips! Will try them out and let you know how it goes.

**Comment by victorlin** [comment]
@cmdcolin updates per suggestion:

1. This works and should be a good short-term solution. However, attempts to load `LinearPileupDisplay` or `LinearSNPCoverageDisplay` result in this browser console error ([example](https://dev-jbrowse.serratus.io/jbrowse?bam=SRR9966509&loc=MG197718.1)):
    > Uncaught Error: [mobx-state-tree] Cannot resolve a reference to type '(LinearPileupDisplayConfigurationSchema | LinearSNPCoverageDisplayConfigurationSchema | LinearAlignmentsDisplayConfigurationSchema | LinearBareDisplayConfigurationSchema | LinearBasicDisplayConfigurationSchema | LinearReferenceSequenceDisplayConfigurationSchema | ChordVariantDisplayConfigurationSchema | LinearVariantDisplayConfigurationSchema | LinearWiggleDisplayConfigurationSchema)' with id: 'SRR9966509-LinearPileupDisplay' unambigously, there are multiple candidates: /config/tracks/0/displays/0/pileupDisplay, /config/tracks/0/displays/1

    Not a huge deal since `LinearAlignmentsDisplay` is already a combination of both.
2. Downgrading to 1.1.0 results in this runtime error which fails to render the component:
    ```
    Error: A React component suspended while rendering, but no fallback UI was specified.

    Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
        in Unknown (created by JBrowseLinearGenomeView)
        in div (created by ForwardRef(Paper))
        in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
        in WithStyles(ForwardRef(Paper)) (created by ViewContainer)
        in div (created by ForwardRef(Paper))
        in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
        in WithStyles(ForwardRef(Paper)) (created by ViewContainer)
        in ViewContainer (created by JBrowseLinearGenomeView)
        in div (created by JBrowseLinearGenomeView)
        in JBrowseLinearGenomeView (at Jbrowse.jsx:103)
        ...
    ```

**Comment by cmdcolin** [comment]
there is a new version 1.3.2 that has a couple fixes, not sure if it specifically addresses all the concerns but welcome to try it out

**Comment by victorlin** [comment]
@cmdcolin thanks! It feels much snappier compared to 1.3.0. We'll be going forwards with this one.

**Comment by cmdcolin** [comment]
this is quite cool! one random thing is that, sometimes, it's hard to see where to navigate to see the reads. e.g. if i click frank the bat, the default contig that is selected is NC_045512.2 but there are no reads that are mapped to that contig. have to manually inspect the BAM and find that the reads are mapped to e.g. EU769558.1

not sure if there is an easy fix, or whether jbrowse can help there

**Comment by victorlin** [comment]
@cmdcolin I guess the JBrowse link at the top of the page isn't very useful. Typically, you'll want to use one of the sequence-level matches which will directly link to reads associated with a specific sequence (or JBrowse `location`). *Show all regions in assembly* is also uninformative since we have too many sequence names associated with each BAM.

serratus-jbrowse-links

@ababaian should we remove the top JBrowse link?

Direct links for comparison:

- https://serratus.io/jbrowse?bam=ERR2756788
- https://serratus.io/jbrowse?bam=ERR2756788&loc=EU769558.1

**Pull request merged**
