### PR TITLE
Geo histogram (#230)

### PR DESCRIPTION
**Pull request by ababaian**
Pardon my misuse of git if this isn't the ideal way to do this, but to get the [geo-histogram](https://github.com/serratus-bio/serratus.io/pull/229) branch from @khanzardar onto this repo as it's own branch (not merged into `main`). I accepted it onto this `geo_time` branch and now am opening a PR to go from serratus.io:geo_time into serratus.io:main.

* timeline component fetching .tsv data and attempting to create histogram. Not plotting in monthly increments atm.

* working histogram, plots by month, using d3's max/min to find date ranges

* Able to pass selectedPoints to TimePlot component, if selectedPoints histogram will adjust to plot on that data - not working flawlessly

* Histogram labels added, histogram will keep full data & allow overlay of selected data

* x-axis will now remain static based off of entire dataset

* updated TODO comment

* fixed prettier warning by running npm command

---------

### Checklist

- [ ] Add tests or provide evidence of manual testing (if applicable)
- [ ] PR checks pass (see [CONTRIBUTING.md](https://github.com/serratus-bio/serratus.io/blob/HEAD/CONTRIBUTING.md) for how to fix failing checks)

### CODE REVIEW

**Comment by ababaian** [comment]
So not building at the moment :*(

**Comment by khanzardar** [comment]
I will take a look into why build is failing.

**Comment by khanzardar** [comment]
Hey @ababaian, it's currently unclear to me why this build is failing. I do see the following error message in the logs:

```
/usr/bin/git ls-remote -h -t ssh://git@github.com/rbuels/librpc-web.git
2023-02-20T18:12:09.6980002Z npm ERR! 
2023-02-20T18:12:09.6983076Z npm ERR! git@github.com: Permission denied (publickey).
2023-02-20T18:12:09.6986466Z npm ERR! fatal: Could not read from remote repository.
2023-02-20T18:12:09.6989672Z npm ERR! 
2023-02-20T18:12:09.6992780Z npm ERR! Please make sure you have the correct access rights
2023-02-20T18:12:09.6996112Z npm ERR! and the repository exists.
```

Have you run into this before?

**Comment by ababaian** [comment]
We keep running into this, need to pin the dependencies for local builds so it matches worker. Or update worker? @victorlin might have some better insight on the optimal choice here.

**Comment by khanzardar** [comment]
@ababaian Okay, I'm able to reproduce error seen by worker on local once I switched to node v14. Appears to be an issue linked with cloning a repo over ssh. See the following link for more information: [https://github.com/npm/cli/issues/2610](https://github.com/npm/cli/issues/2610). 

I'm all ears to any insights you may have. In the meantime, I'll follow the thread above to see possible workaround / solutions.

**Comment by ababaian** [comment]
How do we update the worker build?

**Comment by victorlin** [comment]
> @ababaian: Pardon my misuse of git if this isn't the ideal way to do this, but to get the https://github.com/serratus-bio/serratus.io/pull/229 branch from @khanzardar onto this repo as it's own branch (not merged into main). I accepted it onto this geo_time branch and now am opening a PR to go from serratus.io:geo_time into serratus.io:main.

This sounds reasonable to me (see #232).

> @khanzardar: However I noticed that I running node v16 on local whereas the worker's running on node v14
> @ababaian: How do we update the worker build?

Yeah, this project was built on v14 and both the CI workflow (on GitHub) and the deployed builds (on AWS Amplify) use v14. I do think that we should update to v16 soon though. This was started in #195 but need to dig deeper into build issues.

**Comment by khanzardar** [comment]
I've pushed the updated branch - with reversion to package-lock v1 - onto my forked repo & made a PR to merge into this repo's geo_time. If you agree, we can merge these changes into main to temporary deal with this issue until we decide to upgrade to node v16.

**Comment by ababaian** [comment]
I merged the commit, but still not building

**Comment by victorlin** [comment]
I'm going to merge #195 and update this PR to work with that.

**Comment by ababaian** [comment]
OK Live version is now available at: https://geo-time.serratus.io/ Sorry about the delay

Would you be able to make the width of the plot adjust to the window size so it's say 90% width of the iframe?

**Comment by ababaian** [comment]
@khanzardar bump

**Comment by lukepereira** [comment]
closing in favour of #239

**Pull request closed without merging**
